# Generated by Django 4.1.3 on 2022-11-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedURLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='URL',
            new_name='CarURLModel',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='url',
            new_name='car_url',
        ),
    ]
